# Generated by Django 5.1.3 on 2024-11-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='camera',
            field=models.IntegerField(default=0),
        ),
    ]
